<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:con="http://eviware.com/soapui/config" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:aem="http://valida.aem.gob.cl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://valida.aem.gob.cl">
	<wsdl:documentation>
Documentacion
</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:aem="http://valida.aem.gob.cl" targetNamespace="http://valida.aem.gob.cl" elementFormDefault="qualified">
			<xsd:include schemaLocation="http://valida.aem.gob.cl/documentales/AEM/sobre.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="SRITRTR004Request">
		<wsdl:part name="SRITRTR004Request" element="aem:sobre">
</wsdl:part>
	</wsdl:message>
	<wsdl:message name="SRITRTR004Response">
		<wsdl:part name="SRITRTR004Response" element="aem:sobre">
</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="SRITRTR004">
		<wsdl:operation name="getSRITRTR004">
			<wsdl:input message="aem:SRITRTR004Request">
</wsdl:input>
			<wsdl:output message="aem:SRITRTR004Response">
</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SRITRTR004Soap" type="aem:SRITRTR004">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getSRITRTR004">
			<soap:operation soapAction="http://valida.aem.gob.cl/getSRITRTR004"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="SRITRTR004Service">
		<wsdl:port name="SRITRTR004SoapPort" binding="aem:SRITRTR004Soap">
			<soap:address location="https://SICEX.cl/Interoperabilidad/SRITRTR004"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
